language: node_js

node_js:
  - "4"

notifications:
  email: false
  webhooks:
  urls:
    - https://ci.miloszdura.com/deploy/chat
    on_start: always
    on_success: always
    on_failure: always

script:
  - gulp build